{"uuid": "0e5ba6ba-d52d-4913-a1a3-7df443f7a490", "children": ["4f27a04a-ecfa-4ad1-9bf2-02e5cd52a93b", "8432329c-a3cb-48d0-b598-c9b85c2c9b06"], "befores": [{"name": "init_login", "status": "passed", "start": 1738050718018, "stop": 1738050719666}], "afters": [{"name": "init_login::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\T\\Desktop\\毕设\\NWU_Campus_UI_Auto_Test\\script\\test_login.py\", line 16, in init_login\n    DriverUtils.quit_driver()\n  File \"C:\\Users\\T\\Desktop\\毕设\\NWU_Campus_UI_Auto_Test\\utils.py\", line 25, in quit_driver\n    cls.driver.quit()\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 85, in quit\n    RemoteWebDriver.quit(self)\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 522, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 236, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 415, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 446, in _request\n    self._conn.request(method, parsed_url.path, body, headers)\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1336, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1382, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1331, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1091, in _send_output\n    self.send(msg)\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1035, in send\n    self.connect()\n  File \"C:\\Program Files\\Python312\\Lib\\http\\client.py\", line 1001, in connect\n    self.sock = self._create_connection(\n                ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python312\\Lib\\socket.py\", line 857, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1738050756103, "stop": 1738050762268}], "start": 1738050718018, "stop": 1738050762268}